//
//  ListModels.swift
//  Journey
//
//  Created by  Mikhail on 01.03.2021.
//  Copyright (c) 2021  Mikhail. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum ListOfRoutes {
    // MARK: Use cases
    
    enum DisplayRoutes {
        struct Request {
        }
        
        struct Response {
            var routes: Results<Route>!
        }
        
        struct ViewModel {
            var routes: Results<Route>!
        }
    }
    enum DeleteRow {
        struct Request {
            var route: Route
        }
        
        struct Response {
            var routes: Results<Route>!
        }
        
        struct ViewModel {
            var routes: Results<Route>!
        }
    }
}
