//
//  ListPresenter.swift
//  Journey
//
//  Created by  Mikhail on 01.03.2021.
//  Copyright (c) 2021  Mikhail. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol ListPresentationLogic {
    func presentRoutes(response: ListOfRoutes.DisplayRoutes.Response)
    func presentDeleteRoute(response: ListOfRoutes.DeleteRow.Response)
    func presentRouteDetails()
}

class ListPresenter: ListPresentationLogic {
    
    weak var viewController: ListDisplayLogic?
    
    // MARK: Do something
    
    func presentRoutes(response: ListOfRoutes.DisplayRoutes.Response) {
        let viewModel = ListOfRoutes.DisplayRoutes.ViewModel(routes: response.routes)
        viewController?.displayRoutes(viewModel: viewModel)
    }
    func presentDeleteRoute(response: ListOfRoutes.DeleteRow.Response) {
        let viewModel = ListOfRoutes.DeleteRow.ViewModel(routes: response.routes)
        viewController?.displayDeleteRoute(viewModel: viewModel)
    }
    func presentRouteDetails() {
        viewController?.displayRouteDetails()
    }
}
