//
//  MapModels.swift
//  Journey
//
//  Created by  Mikhail on 06.02.2021.
//  Copyright (c) 2021  Mikhail. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit
import RealmSwift
enum Map {
    // MARK: Use cases
    
    enum LocationServicesRequest {
        struct Request {
        }
        
        struct Response {
            var success: Bool
        }
        
        struct ViewModel {
            var success: Bool
            var errorTitle: String?
            var errorMessage: String?
        }
    }
    
    enum HealthKitRequest {
        struct Request {
        }
        struct Response {
            var success: Bool
        }
        
        struct ViewModel {
        }
    }
    
    enum GetCurrentLocation {
        struct Request {
            var success: Bool
            var error: NSError?
        }
        
        struct Response {
            var success: Bool
            var error: NSError?
        }
        
        struct ViewModel {
            var success: Bool
            var errorTitle: String?
            var errorMessage: String?
        }
    }
    
    enum CenterMap {
        struct Request {
            var coordinates: CLLocation
        }
        struct Response {
            var coordinates: CLLocation
        }
        struct ViewModel {
            var coordinates: CLLocationCoordinate2D
        }
    }
    
    enum SavingRoute {
        struct Request {
            var location: CLLocation
        }
        struct Response {
            var route: Route
        }
        struct ViewModel {
            var coordinates: [CLLocationCoordinate2D]
            var currentSpeed: Double
            var timeString: String
            var distance: Double
            var avgSpeed: Double
            var steps: Int
        }
    }
    
    enum StopSavingRoute {
        struct Request {
            var name: String
            var image: UIImage?
        }
        struct Response {
            var route: Route
        }
        struct ViewModel {
            var route: Route
        }
    }
    
}
