//
//  MapRouter.swift
//  Journey
//
//  Created by  Mikhail on 06.02.2021.
//  Copyright (c) 2021  Mikhail. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MapRoutingLogic {
    func routeToRouteList(segue: UIStoryboardSegue?)
}

protocol MapDataPassing {
    var dataStore: MapDataStore? { get }
    func passDataToRouteList(source: MapDataStore, destination: inout ListDataStore)
}

class MapRouter: NSObject, MapRoutingLogic, MapDataPassing {
    
    weak var viewController: MapViewController?
    var dataStore: MapDataStore?
    
    // MARK: Routing
    
    func routeToRouteList(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let navigationVC = segue.destination as! UINavigationController
        let destinationVC = navigationVC.viewControllers.first as! ListViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToRouteList(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ListViewController") as! ListViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToRouteList(source: dataStore!, destination: &destinationDS)
        navigateToRouteListViewController(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToRouteListViewController(source: MapViewController, destination: ListViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToRouteList(source: MapDataStore, destination: inout ListDataStore) {
        guard let route = source.route else { return }
        ListWorker.saveRoute(route)
    }
}
