//
//  DetailsInteractor.swift
//  Journey
//
//  Created by  Mikhail on 29.03.2021.
//  Copyright (c) 2021  Mikhail. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func prepareData(request: Details.FillView.Request)
}

protocol DetailsDataStore {
    var route: Route? { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore {
    var route: Route?
    
    
    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker?
    
    func prepareData(request: Details.FillView.Request) {
        
        guard let route = route else { return }
        print("interactor in")
        guard let from = route.timeStamps.first, let to = route.timeStamps.last else { return }
        worker = DetailsWorker()
        let photos = worker?.getPhotos(fromDate: from, toDate: to)
        let response = Details.FillView.Response(route: route, photos: photos)
        presenter?.presentData(response: response)
        print("interactor out")
    }
}
