//
//  DetailsInteractor.swift
//  Journey
//
//  Created by  Mikhail on 29.03.2021.
//  Copyright (c) 2021  Mikhail. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func prepareImage(request: Details.SetImage.Request)
    func prepareStats(request: Details.SetStatistic.Request)
    func prepareData(request: Details.ShowPhotos.Request)
}

protocol DetailsDataStore {
    var route: Route? { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore {
    var route: Route?
    
    
    var presenter: DetailsPresentationLogic?
    var worker: DetailsWorker?
    
    func prepareStats(request: Details.SetStatistic.Request) {
        guard let route = route else { return }
        let response = Details.SetStatistic.Response(route: route)
        presenter?.presentStats(response: response)
    }
    func prepareImage(request: Details.SetImage.Request) {
        guard let data = route?.imageData, let image = UIImage(data: data) else { return }
        let response = Details.SetImage.Response(image: image)
        presenter?.presentImage(response: response)
    }
    
    func prepareData(request: Details.ShowPhotos.Request) {
        
        guard let route = route else { return }
        guard let from = route.timeStamps.first, let to = route.timeStamps.last else { return }
        worker = DetailsWorker()
        let photos = worker?.getPhotos(fromDate: from, toDate: to)
        let response = Details.ShowPhotos.Response(route: route, photos: photos)
        presenter?.presentData(response: response)
    }
}
