//
//  DetailsPresenter.swift
//  Journey
//
//  Created by  Mikhail on 29.03.2021.
//  Copyright (c) 2021  Mikhail. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentData(response: Details.FillView.Response)
}

class DetailsPresenter: DetailsPresentationLogic {
    
    weak var viewController: DetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentData(response: Details.FillView.Response) {
        let viewModel = Details.FillView.ViewModel(route: response.route, photos: response.photos)
        viewController?.displayData(viewModel: viewModel)
    }
}
